### PR TITLE
set_title_enc  should remove TIT2 not TSOT

### PR DESCRIPTION
**Pull request by Bilalh**
TIT2   The 'Title'
TSOT The 'Title sort order'

### CODE REVIEW

**Comment by jameshurst** [comment]
The implementation of `add_text_frame_enc` already causes the previous TIT2 frame to be removed. I decided to remove TSOT when changing the title since I figured that if the title had changed then the title sort order would no longer be accurate. The same is done when setting the album.

If this is an inconvenience then I could add separate methods to manage the sort orders.

**Comment by Bilalh** [comment]
The problem I was having was that when calling  `set_title` I was ending up with multiple TIT2 frames i.e the old TIT2 frames was not removed.  Removing TSOT Does  seam sensible

**Comment by jameshurst** [comment]
In `add_text_frame_enc` the previous TIT2 frame should be removed by `self.remove(&id[..])`. The previous TIT2 frame gets removed for me. Does this only happen with a specific file or id3 version?

**Comment by Bilalh** [comment]
I tried on 5 tracks from 5 different albums  all id3 2.4  which have the same problem. An example https://dl.dropboxusercontent.com/u/6818584/01%20%E8%8A%B1%E6%A8%99.mp3

**Comment by jameshurst** [comment]
I just tried using the file you linked and the code below and I'm only seeing one TIT2 frame in the after loop.

```rust
let mut tag = id3::Tag::read_from_path("test.mp3").unwrap();
 
println!("BEFORE: ");
for frame in tag.frames().iter() {
    match frame.content {
        Content::Text(ref text) => {
            println!("{}: {}", frame.id, text);
        }
        _ => {
            println!("{}", frame.id);
        }
    }
}
 
println!("\n");
 
tag.set_title("TEST TITLE");
 
println!("AFTER: ");
for frame in tag.frames().iter() {
    match frame.content {
        Content::Text(ref text) => {
            println!("{}: {}", frame.id, text);
        }
        _ => {
            println!("{}", frame.id);
        }
    }
}
```

**Comment by jameshurst** [comment]
Hmm, I'm still not seeing any TIT2 tag being kept using that mp3 file and the code snippet you posted. Are you sure you're using the latest version of rust-id3?

**Comment by Bilalh** [comment]
I using the latest 0.14, build by cargo.


To make it more clear,  I run this code  using `cargo run`  
```
mod music;

extern crate id3;
use id3::Tag;

fn main(){
    let p = "test.mp3";
    let mut tag = Tag::read_from_path(p).unwrap();
    tag.set_title("Flower Sign");
    tag.add_comment("", "Hello");
    tag.save();
}
```

**Comment by Bilalh** [comment]
I using the latest 0.14, build by cargo and using rust 1.0,  I rebuilded to make sure.
```
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
```

To make it more clear,  I run the exact code below  **3 times** on the linked mp3  using `cargo run`  
This resulted in  **three** TIT2 tags in the mp3

```
// main.rs
mod music;

extern crate id3;
use id3::Tag;

fn main(){
    let p = "test.mp3";
    let mut tag = Tag::read_from_path(p).unwrap();
    tag.set_title("Flower Sign");
    tag.add_comment("", "Hello");
    tag.save();
}
```

Changing the empty string to any else i.e `tag.add_comment("desc", "Hello");` and it worked correctly with only one TIT2 tag in the mp3

**Comment by jameshurst** [comment]
Fixed in https://github.com/jameshurst/rust-id3/commit/e2b9483a578d590031658c67dce01ec49fa20b3f and version 0.1.5.

Turns out it was an issue with the modified offset of the file being set incorrectly when removing comments.

**Pull request closed without merging**
