### PR TITLE
use caret instead of tilde requirements, delete cargo lock

### PR DESCRIPTION
**Pull request by jxs**
same as https://github.com/jameshurst/rust-metaflac/pull/5

thanks

### CODE REVIEW

**Comment by polyfloyd** [comment]
IIRC, I was the one who comitted Cargo.lock to git because I thought it should always be to allow reproducible builds. TIL :)

Before we merge your PR, could you add Cargo.lock to .gitignore?

**Comment by jxs** [comment]
done :)

**Comment by jxs** [comment]
can you also publish this updates on cargo?

**Comment by polyfloyd** [comment]
Done!

**Comment by jxs** [comment]
thanks!

**Pull request merged**
